"""MAP-7 step 7: dbt staging model scaffolding from a finalized MappingDefinition.

Generates a best-effort `stg_{source}_{table}.sql` stub in the standard dbt
staging-model shape (`source` CTE -> `renamed` CTE -> final `select`). This
repo doesn't have access to the actual `stg_pas*_*.sql` conventions --
those live in the separate warehouse repo (see CLAUDE.md's "Relationship to
other repos") -- so the exact column formatting there may differ. Treat
the output as a starting point for a human to adjust, not a drop-in
replacement; the generated file says so in its header comment.

Column order follows the target canonical schema's declaration order
(`canonical/registry.py`'s `get_fields`), not the source file's column
order -- matches "the staging model's CAST'd output is the authoritative
target shape" (docs/mapper-agent-roadmap.md).
"""

from __future__ import annotations

from .canonical import registry as canonical_registry
from .models import MappingDefinition

_HEADER = """\
-- Auto-generated by schema_inference (MAP-7 dbt scaffolding). Review and
-- adjust before merging -- this is a best-effort CTE/CAST shape only;
-- the real stg_pas*_*.sql conventions live in the separate warehouse repo.
-- Source: {source_name}.{table_name}
-- Reviewer: {reviewer_identity}
-- Reviewed at: {reviewed_at}
"""


def _quote_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _hardcoded_expr(value: str | None, target_type: str) -> str:
    if value is None:
        return "NULL"
    if target_type in ("string", "date"):
        return _quote_literal(value)
    return value


def generate_staging_model_sql(definition: MappingDefinition) -> str:
    schema_key = canonical_registry.schema_for_table(definition.table_name)
    fields = canonical_registry.get_fields(schema_key)

    approved_by_target = {
        a.target_field: a for a in definition.approved_mappings if a.target_field
    }
    resolutions_by_field = {r.target_field: r for r in definition.missing_field_resolutions}

    select_lines: list[str] = []
    for f in fields:
        approved = approved_by_target.get(f.name)
        if approved is not None:
            select_lines.append(f"        {approved.sql_expression} as {f.name}")
            continue

        resolution = resolutions_by_field.get(f.name)
        if resolution is None:
            select_lines.append(f"        NULL as {f.name}")
        elif resolution.resolution == "NULL":
            select_lines.append(f"        NULL as {f.name}")
        elif resolution.resolution == "HARDCODED":
            expr = _hardcoded_expr(resolution.hardcoded_value, f.target_type)
            select_lines.append(f"        {expr} as {f.name}")
        else:  # DERIVED
            select_lines.append(f"        {resolution.derivation_sql} as {f.name}")

    if definition.extended_attributes:
        pairs = ", ".join(
            f"'{col}', {col}" for col in definition.extended_attributes
        )
        extended_expr = f"object_construct({pairs})"
    else:
        extended_expr = "NULL"
    select_lines.append(f"        {extended_expr} as extended_attributes")

    header = _HEADER.format(
        source_name=definition.source_name,
        table_name=definition.table_name,
        reviewer_identity=definition.reviewer_identity,
        reviewed_at=definition.reviewed_at.isoformat(),
    )

    return (
        f"{header}\n"
        "with source as (\n\n"
        f"    select * from {{{{ source('{definition.source_name}', '{definition.table_name}') }}}}\n\n"
        "),\n\n"
        "renamed as (\n\n"
        "    select\n"
        + ",\n".join(select_lines)
        + "\n\n    from source\n\n"
        ")\n\n"
        "select * from renamed\n"
    )
